Muli_Pariwar_Lagat/Areas/pariwarlagat/Controllers/LoginController.cs
using Muli_Pariwar_Lagat.Models;
using Muli_Pariwar_Lagat.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Muli_Pariwar_Lagat.Areas.pariwarlagat.Controllers
{
    [AllowAnonymous]
    public class LoginController : Controller
    {
       
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(LoginViewModel lvm, string ReturnUrl)
        {
            if (ModelState.IsValid)
            {
                if (Membership.ValidateUser(lvm.UserName, lvm.Password))
                {
                    FormsAuthentication.SetAuthCookie(lvm.UserName ,true);

                    if (ReturnUrl != null)
                    {
                        return Redirect(ReturnUrl);
                    }
                    else if (ReturnUrl == null && lvm.UserName == "admin")
                    { return Redirect("~/pariwarlagat/Dashboard"); }
                    else
                    {
                        return Redirect("~/Home/Index");
                    }




                }

            }
            return View(lvm);
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return Redirect("~/pariwarlagat/Login");
        }
    }
}

Muli_Pariwar_Lagat/Areas/pariwarlagat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PariwarLagat", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
               @*
                <ul class="nav navbar-nav navbar-right">
                    <a href="~/Login/Logout"> Logout</a>
                    <li>@Html.ActionLink("Logout", "Logout", "Login")</li>

                </ul>
                *@
                @Html.Partial("_LoginPartial")
            </div>
           
           @* <div class="pull-right">

                    <a href="~/Login/Logout"> Logout</a>
    </div>*@
        </div>
    </div>
    

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>